name: Simple

on: [push]

jobs:
  build_binder:
    runs-on: ubuntu-latest
    name: 'Creating a binder'
    steps:
    - name: 'Build and push image'
      uses: neovintage/repo2docker-action@master
